name: terraform-aws

on:
  push:
    branches: [ "**" ]
    paths:
      - "*.tf"
      - "*.tfvars"
      - ".github/workflows/terraform-aws.yml"
  pull_request:
    branches: [ "**" ]
    paths:
      - "*.tf"
      - "*.tfvars"
      - ".github/workflows/terraform-aws.yml"
  workflow_dispatch:
    inputs:
      var_file:
        description: "Chemin du .tfvars (optionnel, ex: prod.tfvars)"
        required: false
        default: ""
      apply:
        description: "Exécuter terraform apply ? (true/false)"
        required: true
        default: "false"

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: eu-west-1
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

concurrency:
  group: tf-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .   # <<< racine du repo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.5"

      # Cache providers/plugins Terraform à la racine
      - name: Restore Terraform plugin cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            ./.terraform
          key: tf-${{ runner.os }}-${{ hashFiles('**/*.tf', '.terraform.lock.hcl') }}
          restore-keys: |
            tf-${{ runner.os }}-

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        env:
          TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        env:
          TF_CLI_ARGS_plan: "-no-color"
        run: |
          set -euo pipefail
          if [ -n "${{ github.event.inputs.var_file }}" ]; then
            terraform plan -out=tfplan -var-file="${{ github.event.inputs.var_file }}"
          else
            terraform plan -out=tfplan
          fi
          terraform show -no-color tfplan > tfplan.txt

      - name: Comment plan on PR
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          filePath: tfplan.txt
          message: |
            ### Terraform plan result
            <details><summary>Show plan</summary>

            ```diff
            ${{ steps.plan.outcome == 'success' && join(fromJSON('[""]'), '') || '' }}
            ```
            </details>

      - name: Save Terraform plugin cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            ./.terraform
          key: tf-${{ runner.os }}-${{ hashFiles('**/*.tf', '.terraform.lock.hcl') }}

      - name: Terraform apply
        if: >
          (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main'))
          || (github.event_name == 'workflow_dispatch' && github.event.inputs.apply == 'true')
        env:
          TF_CLI_ARGS_apply: "-auto-approve -no-color"
        run: terraform apply -auto-approve tfplan
